source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

link_with 'Twitter Demo', 'Flickr Demo'

pod 'AFNetworking/UIKit', '~> 2.5.0'
pod 'BBlock/UIKit', '~> 1.2.0'
pod 'BDBOAuth1Manager', :path => '../'
