source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

link_with 'Twitter Demo', 'Flickr Demo'

pod 'AFNetworking/UIKit', '~> 3.0.0'
pod 'BBlock/UIKit', '~> 1.2.0'
pod 'BDBOAuth1Manager', :path => '../'
