source 'https://github.com/CocoaPods/Specs.git'

abstract_target "iOS" do
  platform :ios, '8.0'

  pod 'AFNetworking/UIKit', '~> 2.6.0'
  pod 'BBlock/UIKit', '~> 1.2.0'
  pod 'BDBOAuth1Manager', :path => '../'

  target 'Twitter Demo' do
  end

  target 'Flickr Demo' do
  end

  target 'BDBOAuth1ManagerTests-iOS' do
  end
end

abstract_target "OSX" do
  platform :osx, '10.9'

  pod 'BDBOAuth1Manager', :path => '../'

  target 'BDBOAuth1ManagerTests-OSX' do
  end
end
